config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  excludes: []

comments:
  active: true
  UndocumentedPublicClass:
    active: true
    searchInNestedClass: false
    excludes: &test_and_sample_excludes
      - '**/samples/**'
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/androidUnitTest/**'
      - '**/androidInstrumentedTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
      - '**/testFixtures/**'
  UndocumentedPublicFunction:
    active: false
    excludes: *test_and_sample_excludes
  UndocumentedPublicProperty:
    active: false
    excludes: *test_and_sample_excludes

complexity:
  active: true
  ComplexCondition:
    active: true
    allowedConditions: 4
  CyclomaticComplexMethod:
    active: true
    allowedComplexity: 15
    excludes: &test_excludes
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/androidUnitTest/**'
      - '**/androidInstrumentedTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
      - '**/testFixtures/**'
  LargeClass:
    active: true
    allowedLines: 600
    excludes: *test_excludes
  LongMethod:
    active: true
    allowedLines: 70
    excludes: *test_excludes
  LongParameterList:
    active: true
    allowedFunctionParameters: 8
    allowedConstructorParameters: 7
    ignoreDefaultParameters: true
    ignoreDataClasses: true
  TooManyFunctions:
    active: true
    excludes: *test_excludes
    allowedFunctionsPerFile: 12
    allowedFunctionsPerClass: 12
    allowedFunctionsPerInterface: 12
    allowedFunctionsPerObject: 15
    allowedFunctionsPerEnum: 12
    ignoreAnnotatedFunctions: ['Preview']

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    excludes: *test_excludes
    allowedExceptionNameRegex: '_|(ignore|expected).*'

naming:
  active: true
  MatchingDeclarationName:
    active: false
  FunctionNaming:
    active: true
    aliases:
      - 'FunctionName'
    excludes: *test_excludes
    functionPattern: '[A-Za-z][a-zA-Z0-9]*'
    excludeClassPattern: '$^'
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    active: false
  VariableNaming:
    active: true
    aliases:
      - 'PropertyName'
    variablePattern: '[a-zA-Z][A-Za-z0-9_]*'
    privateVariablePattern: '(_)?[a-zA-Z][A-Za-z0-9_]*'
    excludeClassPattern: '$^'

style:
  active: true
  ReturnCount:
    active: true
    max: 10
    excludeGuardClauses: true
    excludedFunctions:
      - 'equals'
      - 'hashCode'
      - 'toString'
  ThrowsCount:
    active: true
    max: 2
    excludeGuardClauses: true
  UnusedParameter:
    active: true
    excludes: *test_excludes
    allowedNames: '(ignored|expected|serialVersionUID)'
  UnusedPrivateFunction:
    active: true
    excludes: *test_excludes
    ignoreAnnotated: ['Preview']
  MagicNumber:
    active: true
    excludes:
      - '**/*.gradle.kts'
      - '**/build-logic/**'
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/jvmTest/**'
      - '**/androidUnitTest/**'
      - '**/androidInstrumentedTest/**'
      - '**/jsTest/**'
      - '**/iosTest/**'
      - '**/testFixtures/**'
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  MaxLineLength:
    active: true
    excludes: *test_excludes
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeRawStrings: true
  NewLineAtEndOfFile:
    active: false
